/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.solai.solai_game_simulator

import org.solai.solai_game_simulator.character_queue.GameSimulationData
import org.solai.solai_game_simulator.character_queue.RedisSimulationQueue
import org.solai.solai_game_simulator.character_queue.SimulationQueue
import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication
import sol_game.CharacterConfigLoader
import java.lang.IllegalStateException
import java.util.*

@SpringBootApplication
class App

fun main(args: Array<String>) {
    SpringApplication.run(App::class.java, *args)
//    testQueue()
}

fun postExampleCharToQueue() {
    val charQ: SimulationQueue = SimulationQueue.getQueue("localhost") ?: run {
        throw IllegalStateException("Could not connect to simulation queue")
    }

    val charConfig = CharacterConfigLoader.fromResourceFile("frankCharacterConfig.json")

    charQ.pushSimulationData(GameSimulationData(
            UUID.randomUUID().toString(),
            listOf(charConfig, charConfig),
            listOf("gameLength", "nearDeathScenerios")
    ))
}


fun testQueue() {

    val charQ: SimulationQueue = SimulationQueue.getQueue("localhost") ?: run {
        throw IllegalStateException("Could not connect to simulation queue")
    }


    Thread() {
        var i = 0
        while (true) {
            val charQ2:  SimulationQueue = SimulationQueue.getQueue("localhost")!!
            charQ2.pushSimulationData(GameSimulationData(
                    simulationId = "sim1 $i",
                    charactersConfigs = listOf(),
                    metrics = listOf("hei")
            ))
            i++
            Thread.sleep(1000)
        }

    }.start()

    while (true) {
        val simData = charQ.waitSimulationData(3)
        println(simData)
        Thread.sleep(3000)
    }

}