/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.solai.solai_game_simulator

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication
class WebAppEntry

fun main(args: Array<String>) {
    SpringApplication.run(WebAppEntry::class.java, *args)
}